### ISSUE TITLE
Creating pattern link this

### ISSUE THREAD

**Issue by vansh-patel-8123** [thecodingcenter/java#5]
* * * * * * 
         * * * * * 
          * * * * 
           * * * 
            * * 
             * 
             * 
            * * 
           * * * 
          * * * * 
         * * * * * 
        * * * * * *

**Comment by vansh-patel-8123** [comment]
hey @thecodingcenter assign hacktoberfest label to this problem

**Comment by thecodingcenter** [comment]
yes y not

**Comment by thecodingcenter** [comment]
just send me a pull request

**Comment by ArcheR1901** [comment]
On it

**Comment by vansh-patel-8123** [comment]
I completed task please merge the branch and add hacktoberfest label
